    print("******************************************")
    print("HOLO - FRESNEL ZONE PLATE")
    print("Beam Size at FZP Hor FWHM = {0:.3f} um".format(2.355 * beam.size_rms * 1e6))
    # print('Beam Size at FZP Vert FWHM = {0:.3f} um'.format(divy*2.355*(31/55)*(120-86)))
    print("FZP focal distance = {0:.3f} mm".format(lens.f * 1e3))
    print("FZP Diameter = {0:.1f} \u03BCm".format(lens.diameter * 1e6))
    print("FZP NA = {0:.4f}".format(lens.numerical_aperture))
    print("FZP Number of zones = {0:d}".format(lens.N_zones))
    print("FZP Outer zone width = {0:.1f} nm".format(lens.rn * 1e9))
    print("FZP Inner zone width = {0:.1f} nm".format(r1 * 1e9))
    print("FZP DOF = {0:.3f} um".format(lens.dof * 1e6))
    # print('FZP Magnification = {0:.1f}'.format(mag_fzp))
    # print('FZP WD = {0:.3f} mm'.format(q*1e3))
    print("FZP Thickness = {0:.3f} um".format(lens.thickness * 1e6))
    print("FZP Aspect Ratio = {0:.3f}".format(lens.aspect_ratio))
    print("b-stop = {0:.3f}".format(b_stop))
    print("OSA WD = {0:.3f} mm".format(OSA_wd * 1e3))
    print("OSA aperture = {0:.3f} um".format(OSA_app * 1e6))
    print("Focus Size Horizontal = {0:.3f} um".format(2.355 * size_out * 1e6))
    # print('Focus Size Vertical = {0:.3f} um'.format(focusy))
    # print('Focus Size Horizontal = {0:.3f} um'.format(resolution*1e6))
    # print('Focus Size Vertical = {0:.3f} um'.format(resolution*1e6))
    print("******************************************")